# Generated by Django 3.0.2 on 2020-01-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteration',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='comment'),
        ),
    ]
