# Generated by Django 3.0.2 on 2020-01-24 14:48

from django.db import migrations, models
import django.db.models.deletion
import team.models as lib


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200123_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteration',
            options={'ordering': ('-start',)},
        ),
        migrations.AlterField(
            model_name='iteration',
            name='start',
            field=models.DateField(default=lib.iteration_start, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='stop',
            field=models.DateField(default=lib.iteration_stop, verbose_name='stop'),
        ),
        migrations.AlterField(
            model_name='report',
            name='iteration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='team.Iteration'),
        ),
    ]
