# Generated by Django 3.0.2 on 2020-01-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20200124_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='url',
            field=models.URLField(db_index=True, verbose_name='url'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('iteration', 'task')},
        ),
    ]
