# Generated by Django 3.0.2 on 2020-02-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20200124_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='delegation',
            field=models.CharField(choices=[('tell', 'Tell'), ('sell', 'Sell'), ('consult', 'Consult'), ('agree', 'Agree'), ('advise', 'Advise'), ('inquire', 'Inquire'), ('delegate', 'Delegate')], default='agree', max_length=32, verbose_name='delegation'),
        ),
    ]
