# Generated by Django 3.0.2 on 2020-02-01 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_report_delegation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='iteration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='team.Iteration', verbose_name='iteration'),
        ),
        migrations.AlterField(
            model_name='report',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Task', verbose_name='task'),
        ),
        migrations.AlterField(
            model_name='report',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Worker', verbose_name='worker'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Tracker', verbose_name='tracker'),
        ),
    ]
