# Generated by Django 4.0.2 on 2022-02-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_worker_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='no_export',
            field=models.BooleanField(default=False, verbose_name='no export'),
        ),
    ]
