# Generated by Django 5.0.7 on 2024-07-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0008_worker_no_export"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"ordering": ("name", "email")},
        ),
        migrations.AddField(
            model_name="worker",
            name="disabled",
            field=models.BooleanField(default=False, verbose_name="disabled"),
        ),
    ]
