# Generated by Django 5.0.7 on 2024-08-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0009_alter_worker_options_worker_disabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"ordering": ("order", "name", "email")},
        ),
        migrations.AddField(
            model_name="worker",
            name="order",
            field=models.IntegerField(default=0, verbose_name="order"),
        ),
    ]
