# Generated by Django 5.1 on 2024-08-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0011_rename_iteration_start_stop_start_stop_idx"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="iteration",
            new_name="start_stop_index",
            old_name="start_stop_idx",
        ),
    ]
